"""Add championship_id to payment_records

Revision ID: 8126f542a734
Revises: 4b9bedb9afa4
Create Date: 2024-10-23 23:43:50.268742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8126f542a734'
down_revision: Union[str, None] = '4b9bedb9afa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_records', sa.Column('championship_id', sa.Integer(), nullable=True))
    op.add_column('payment_records', sa.Column('hourly_rate', sa.Float(), nullable=True))
    op.add_column('payment_records', sa.Column('bonus', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'payment_records', 'championships', ['championship_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_records', type_='foreignkey')
    op.drop_column('payment_records', 'bonus')
    op.drop_column('payment_records', 'hourly_rate')
    op.drop_column('payment_records', 'championship_id')
    # ### end Alembic commands ###
