version: "3.8"

services:
  web:
    build: .
    container_name: waveshub_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: wavesHub_db
    restart: always
    environment:
      POSTGRES_USER: wavesHub_user
      POSTGRES_PASSWORD: WavesHub
      POSTGRES_DB: wavesHub_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
